name: ci

on:
  - push
  - pull_request

jobs:

  preinstall:
    name: Continuous integration (preinstall)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2

      - name: Install ğŸ’¾
        uses: meteor-actions/install@v1

  build:
    needs: ["preinstall"]
    name: Continuous integration (build)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2

      - name: Install ğŸ’¾
        uses: meteor-actions/install@v1

      - name: Build ğŸ—ï¸
        run: meteor build ../dist

  lint:
    needs: ["preinstall"]
    name: Continuous integration (lint)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2

      - name: Install ğŸ’¾
        uses: meteor-actions/install@v1

      - name: Lint ğŸ‘•
        run: meteor npm run lint

  type-check:
    needs: ["preinstall"]
    name: Continuous integration (type check)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2

      - name: Install ğŸ’¾
        uses: meteor-actions/install@v1

      - name: TypeScript check â˜‘ï¸
        run: meteor npm run tsc

  test:
    needs: ["preinstall"]
    name: Continuous integration (tests)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2

      - name: Install ğŸ’¾
        uses: meteor-actions/install@v1

      - name: Tests ğŸ”¬
        run: meteor npm run ci:test

      - name: Publish coverage report ğŸ“°
        uses: codecov/codecov-action@v2
        with:
          flags: test
          directory: ./.coverage/
          fail_ci_if_error: true

  test-app:
    needs: ["preinstall"]
    name: Continuous integration (app tests)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2

      - name: Install ğŸ’¾
        uses: meteor-actions/install@v1

      - name: App Tests ğŸ•¹ï¸
        run: meteor npm run ci:test -- --full-app

      - name: Publish coverage report ğŸ“°
        uses: codecov/codecov-action@v2
        with:
          flags: test-app
          directory: ./.coverage/
          fail_ci_if_error: true
